name: Wait Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 30 seconds
        run: |
          echo "Waiting for 30 seconds..."
          sleep 120
          echo "Wait completed!"
