name: Create Tag on Merge and Publish it to ECR

on:
  pull_request:
    types:
      - closed

jobs:
  create_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create and push new tag
        run: |
          npm run create-tag
          
      - name: Create OPA image
        run: |
          npm run create-tag
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1
          
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build and Push Docker Image to ECR
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.dev-01
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ github.repository }}:latest
