name: Wait Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 300 seconds
        run: |
          echo "Waiting for 300 seconds..."
          sleep 300
          echo "Wait completed!"
