name: Wait Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 20 seconds
        run: |
          echo "Waiting for 20 seconds..."
          sleep 20
          echo "Wait completed!"
