name: Wait Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 150 seconds
        run: |
          echo "Waiting for 150 seconds..."
          sleep 150
          echo "Wait completed!"
