name: Wait Workflow
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 180 seconds
        run: |
          echo "Waiting for 180 seconds..."
          sleep 180
          echo "Wait completed!"
